Docker with Python3.7
codalab/codalab-dockers pull request #4
Opened 2019-10-08 08:39 UTC by Didayolo

Adding an updated Docker with Python3.7 and latest version of usual librairies (numpy, etc.).

We are using it for graduate students course at Université Paris-Saclay but it can be useful more generally.

2019-10-09 21:48 UTC, ckcollab requested changes

2019-10-09 21:48 UTC, ckcollab commented on legacy-py3.7/Dockerfile
> +RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
could we do `FROM` anaconda or some such, instead?

2019-10-11 17:00 UTC, Didayolo commented
So the new version of the Dockerfile is lighter and uses `FROM` anaconda but it seems that anaconda3 is based on Python3.5 (and we wanted Python3.7).

We may stick to the first version (and update it to add some libraries such as tensorflow and imutils).

2019-10-14 18:07 UTC, Didayolo commented
For some reason this new version (`FROM` anaconda3) doesn't work with students' challenges. Code submissions get a "no module named numpy" error even if the libraries are well installed in the docker. Maybe the code doesn't call the Python installed by anaconda. I'll have a look at it soon.

2019-10-17 01:31 UTC, merged